### ISSUE TITLE
Multiple Flex Microforms

### ISSUE THREAD

**Issue by etcmadmax** [CyberSource/cybersource-flex-samples-java#22]
Is it possible to generate multiple Flex microforms on a single page?  I have searched and searched through the documentation and have yet to find a definitive answer to this.  Everything I've seen is the assumption is only one credit card number needs to be tokenized per form.

**Comment by rhidianj** [comment]
This is supported in version 0.4 (specifically the 0.4.4 release). Please specify the Microform clientside library as follows to benefit from the latest patch releases:

```
https://flex.cybersource.com/cybersource/assets/microform/
0.4/flex-microform.min.js
```
