### ISSUE TITLE
Incorrect NPM documentation

### ISSUE THREAD

**Issue by huntwelch** [CyberSource/cybersource-flex-samples-java#26]
Not sure if this is right place, but this is the repo linked from https://www.npmjs.com/package/@cybersource/flex-sdk-web. 

The example shown there uses expiryMonth and expiryYear. It should be cardExpirationMonth and cardExpirationYear; if the example is used as it is shown, the tokenization process will silently strip the junk variables out and return a token with a default expiration date.

**Comment by jadonald** [comment]
Many thanks @huntwelch. The most recent `0.3.1` version fixed up this documentation with the correct payloads.
