### ISSUE TITLE
flex-server-sdk-0.3.2-source.jar is incomplete

### ISSUE THREAD

**Issue by simonzhong1985** [CyberSource/cybersource-flex-samples-java#28]
Hi all, 
I downloaded the flex-server-sdk-0.3.2-source.jar from https://repo1.maven.org/maven2/com/cybersource/flex-server-sdk/0.3.2/ to study the sdk.

However, I found some packages and classes are missing in the source jar file.

 **the structure of flex-server-sdk-0.3.2.jar**

![image](https://user-images.githubusercontent.com/29529035/61777228-2b05b100-ae2f-11e9-83fc-2530f2f2707d.png)

**the structure of flex-server-sdk-0.3.2-source.jar**

![image](https://user-images.githubusercontent.com/29529035/61777246-322cbf00-ae2f-11e9-928f-7fe46b8c55bc.png)

As you see, the imple, internal and repackaged packges are not found in the source jar file. 

Could you help to give some suggestion to download  complete source file?

Thanks.

**Comment by bprokopc** [comment]
Hello @simonzhong1985,
The _flex-server-sdk-0.3.2-source.jar_ contains sources of Flex API server side SDK public interfaces and related POJOs. _flex-server-sdk-0.3.2-source.jar_ (as well as _flex-server-sdk-0.3.2-javadoc.jar_) available on Maven Central are provided to assist IDE's auto-completion and cover client code interactions with Flex API server side SDK.
