### ISSUE TITLE
Cannot read property 'importKey' of undefined

### ISSUE THREAD

**Issue by cody-baker** [CyberSource/cybersource-flex-samples-java#30]
```javascript
import FlexSDKWeb from '@cybersource/flex-sdk-web';

let jwk = await this.generatePublicKey(),
    options = {
         kid: jwk.kid,
         keystore: jwk,
         cardInfo: {
             cardNumber: '4111111111111111',
             cardType: '001',
             expiryMonth: '11',
             expiryYear: '2022',
        },
        encryptionType: 'rsaoaep256',
        production: false,
 };

FlexSDKWeb.createToken(options, (response) => {
    console.log(response);
});
```

TypeError: Cannot read property 'importKey' of undefined
    at y (flex-sdk-web.js?c502:11)
    at eval (flex-sdk-web.js?c502:11)
    at d (flex-sdk-web.js?c502:11)
    at Object.createToken (flex-sdk-web.js?c502:11)
    at VueComponent._callee3$ (AddPaymentMethod.vue?0e2c:456)
    at tryCatch (runtime.js?98b8:45)
    at Generator.invoke [as _invoke] (runtime.js?98b8:274)
    at Generator.prototype.<computed> [as next] (runtime.js?98b8:97)
    at asyncGeneratorStep (cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/AddPaymentMethod.vue?vue&type=script&lang=js&:24)
    at _next (cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/AddPaymentMethod.vue?vue&type=script&lang=js&:26)

This is happening in my localhost development in Chrome version: Version 80.0.3987.149 (Official Build) (64-bit)

**Comment by cody-baker** [comment]
Firefox gives me a more descriptive error: `Argument 2 of SubtleCrypto.importKey is not an object.`

**Comment by jadonald** [comment]
@cody-baker what version of `@cybersource/flex-sdk-web` are you using?
By the looks of things it can't import the key you've provided.
Have you definitely populated the `jwk` variable correctly?

**Comment by cody-baker** [comment]
Using version 0.3.0 of `@cybersource/flex-sdk-web`

We used CyberSource `KeyGenerationApi` and `GeneratePublicKeyRequest` to get the `jwk`. Here is a snippet of that request in python which is essentially a copy of the CyberSource python example for generating a key:
https://developer.cybersource.com/api-reference-assets/index.html#flex_key-generation_generate-key
```python
import json
from CyberSource import *

def get(request):
    try:
        # Reading Merchant details from Configuration file
        key_generation_obj = KeyGenerationApi(cybersource_config)
        key_generation = GeneratePublicKeyRequest(encryption_type="None")
        message_body = json.dumps(key_generation.__dict__)
        return_data, status, body = key_generation_obj.generate_public_key(generate_public_key_request=message_body)

        return HttpResponse(return_data)
    except Exception as e:
        print("Exception when calling KeyGenerationApi->generate_public_key: %s\n" % e)

        return HttpResponse(e)
```

**Comment by jadonald** [comment]
@cody-baker looks like you are creating the key with one type, then specifying differently on the front end.
```python
key_generation = GeneratePublicKeyRequest(encryption_type="None")
```
```js
encryptionType: 'rsaoaep256',
```
You just need these to be the same and what you have will work .

Using `None` is fine for development, however, I would strongly recommend going with `RsaOaep` for your actual integration.

Possible values for `encryptionType` param are:
- `None` - all payloads are in the plain if you inspect the network tab
- `RsaOaep` - card number is encrypted on the device before sending so you won't see this in the network tab.
- `RsaOaep256` - as above but with a different hash used in the encryption. This has slightly less browser support, hence why I would recommend going with `RsaOaep`

Hope this helps

**Comment by cody-baker** [comment]
Ah yes this was an oversight on my end. Bc of this the jwk in the response was None. But even with `RsaOaep` as the `encryptionType` param I am still getting `Cannot read property 'importKey' of undefined` even though I am passing a valid `jwk` now

**Comment by jadonald** [comment]
@cody-baker I wasn't able to recreate this one unfortunately.
We did just push push a `0.3.1` patch this evening, perhaps worth trying with that?

The only occurrence of `importKey` in the codebase where the JWK is being imported via the [WebCryptoAPI](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API).
```js
return window.crypto.subtle.importKey(...);
```
Given the stacktrace, is there perhaps something in your babel setup that could be interfering with it? As a test, perhaps it's worth referencing via a script tag on your page and take your tooling out of the equation?

On a side note, I'd noticed a couple of bugs in the documentation that we fixed up:
- you no longer need to specify the `production: true/false` param
- `expiryMonth` should be `cardExpirationMonth`
- `expiryYear` should be `cardExpirationYear`

The example README on npm shows the correct payloads now for your reference.

**Comment by cody-baker** [comment]
According to [WebCryptoAPI](https://www.chromium.org/blink/webcrypto)

```crypto.subtle is supposed to be undefined in insecure contexts```

And this logs `undefined` in my app:
```javascript
console.log(window.crypto.subtle);
```

Seems like this is the cause of my error because I am testing in ```http://localhost.myWorkDomain.com:8022/``` but we are not able to change this to `https`.

Is there no way of creating tokens in a test environment with `http`?

**Comment by cody-baker** [comment]
@jadonald Looks like I was able to add `https: true` to my `devServer` settings in `vue.config.js` and this got it to work. I appreciate your help on this but I think we are good to go now!

**Comment by jadonald** [comment]
Glad to hear @cody-baker!
